name: File Uploader

on:
  workflow_dispatch:  # เรียกใช้ผ่าน API
    inputs:
      file_path:
        description: 'Path to the file'
        required: true
      file_content:
        description: 'Base64-encoded file content'
        required: true

jobs:
  upload_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Upload File
      run: |
        echo "$FILE_CONTENT" | base64 -d > ${{ github.event.inputs.file_path }}
        git add ${{ github.event.inputs.file_path }}
        git commit -m "Uploaded file via GitHub Actions"
        git push
      env:
        FILE_CONTENT: ${{ github.event.inputs.file_content }}
