name: Use GitHub Token

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Use token from secrets
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # ดึง token จาก Secrets
        run: |
          # ตัวอย่างการใช้ token ในการทำงาน เช่น การเรียก GitHub API
          node your-script.js
