name: Upload Files

on:
  workflow_dispatch: # Trigger manual run
  repository_dispatch: # Trigger by external API

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload File to Repository
      env:
        ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      run: |
        echo "Start Uploading File..."
        curl -X PUT \
          -H "Authorization: token $ACTIONS_TOKEN" \
          -H "Content-Type: application/json" \
          -d @file.json \
          https://api.github.com/repos/<REPO_OWNER>/<REPO_NAME>/contents/<TARGET_PATH>/<FILE_NAME>
